name: Build the container image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

env:
  image_name: ghcr.io/${{ github.repository }}

jobs:

  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the container image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.image_name }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.image_name }}

      - name: Tag and push release image to registry
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.image_name }}:${{ github.event.release.tag_name }}
